server:
  port: 3344

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  cloud:
    zookeeper:
      connect-string: localhost:2181
    config:
      server:
        git:
          # github上面的git地址
          uri: https://gitee.com/sumdi/spring-cloud-config.git
          username: sumdi8512@gmail.com # gitee 用户名
          password: danding.123 # gitee 密码
          search-paths:
            # 文件所处文件夹路径
            - config
          force-pull: true
          refresh-rate: 1
      # 分支名
      label: master
  application:
    name: cloud-config-center
