server:
  port: 8804

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      bindings: # 服务的整合处理
        source1-out-0: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
    function:
      definition: source1
    zookeeper:
      connect-string: localhost:2181