server:
  port: 80

# 服务器名 注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/better?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
logging:
  level:
    # 指定哪个FeignClient接口的请求需要输出日志，以及日志级别
    com.xuyang.springcloud.service.PaymentFeignService: debug

