server:
  port: 8001

# 服务器名 注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/better?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    zookeeper:
      connect-string: localhost:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xuyang.springcloud.common.entity
