###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  ####consul注册中心地址
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/better?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    com.xuyang.springcloud.service: debug

feign:
  hystrix:
    enabled: true
  client:
    config:
      cloud-provider-payment:
        # 连接超时时间
        connectTimout: 5000
        # 读超时时间
        readTimeut: 5000
        # Feign的日志级别
        loggerLevel: full

cloud-provider-payment:
  ribbon:
    OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
    ReadTimeout: 5000   #负载均衡超时时间，默认值5000
    ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
    MaxAutoRetries: 0     #对当前实例的重试次数，默认0
    MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

